tests/docker/run: allow DEBUG to intercept post-command
It's quite possible you want to look at the results after a
build (especially if you want to examine objects). Rather than force the
user to manually configure their build allow a DEBUG=1 invocation to
examine the post-command state.

Signed-off-by: Alex Bennée <alex.bennee@linaro.org>

diff --git a/tests/docker/run b/tests/docker/run
--- a/tests/docker/run
+++ b/tests/docker/run
@@ -68,15 +68,20 @@ echo "* Hit Ctrl-D to continue, or type 'exit 1' to abort"
 echo
 $SHELL
 
-if "$CMD"; then
-    exit 0
-elif test -n "$DEBUG"; then
-    echo "* Command failed:"
+"$CMD"
+RES=$?
+
+if test -n "$DEBUG"; then
+    if test "$RES" -ge 1; then
+        echo "* Command failed ($RES):"
+    else
+        echo "* Command passed:"
+    fi
     echo "  $CMD"
     echo "* Hit Ctrl-D to exit"
     echo
-    # Force error after shell exits
-    $SHELL && exit 1
+    # Exit with command status unless we crash out of the shell
+    $SHELL && exit $RES
 else
-    exit 1
+    exit $RES
 fi
